### ISSUE TITLE
Create About app: Site admin

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six-day-plan#2]
As a **Site Admin**, I can **add an image, a tittle and content** so that **the information become available.**

# ACCEPTANCE CRITERIA

The About app is available to provide users information about the 6 Day-Plan.

# TASKS

- [x] Select a meaningful image
- [x] Add a title
- [x] Create a content explaining about the program
- [x] updated on field
